version: "3.9"

services:
  web:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/data
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./src:/data
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: ["--version"]