version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    privileged: true

  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Tokyo
    working_dir: /data
    privileged: true

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idol_penlight
      TZ: Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    tty: true

volumes:
  db-store:
